// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import libs "desafio-graph/src/libs"
import mock "github.com/stretchr/testify/mock"

// Crawler is an autogenerated mock type for the Crawler type
type Crawler struct {
	mock.Mock
}

// GetPricing provides a mock function with given fields: url
func (_m *Crawler) GetPricing(url string) []libs.Charge {
	ret := _m.Called(url)

	var r0 []libs.Charge
	if rf, ok := ret.Get(0).(func(string) []libs.Charge); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]libs.Charge)
		}
	}

	return r0
}
