// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import structs "desafio-graph/src/structs"

// QueryResolver is an autogenerated mock type for the QueryResolver type
type QueryResolver struct {
	mock.Mock
}

// Sites provides a mock function with given fields: ctx, site
func (_m *QueryResolver) Sites(ctx context.Context, site *string) ([]*structs.Site, error) {
	ret := _m.Called(ctx, site)

	var r0 []*structs.Site
	if rf, ok := ret.Get(0).(func(context.Context, *string) []*structs.Site); ok {
		r0 = rf(ctx, site)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*structs.Site)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, site)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
