// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import graph "desafio-graph/graph"
import mock "github.com/stretchr/testify/mock"

// ResolverRoot is an autogenerated mock type for the ResolverRoot type
type ResolverRoot struct {
	mock.Mock
}

// Query provides a mock function with given fields:
func (_m *ResolverRoot) Query() graph.QueryResolver {
	ret := _m.Called()

	var r0 graph.QueryResolver
	if rf, ok := ret.Get(0).(func() graph.QueryResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.QueryResolver)
		}
	}

	return r0
}
