// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package structs

type Charge struct {
	Name     string `json:"name"`
	BrlValue string `json:"brl_value"`
	UsdValue string `json:"usd_value"`
	EurValue string `json:"eur_value"`
}

type Plans struct {
	Name    string    `json:"name"`
	Charges []*Charge `json:"charges"`
}

type Site struct {
	URL        string   `json:"url"`
	AccessDate string   `json:"access_date"`
	Plans      []*Plans `json:"plans"`
}
